<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RestorantApp.DataAccess\RestorantApp.DataAccess.csproj" />
    <ProjectReference Include="..\RestorantApp.Entity\RestorantApp.Entity.csproj" />
  </ItemGroup>

</Project>
